import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.Scanner;

public class Main {

    public static final double[] REL_H_ENGLISCH = {8.17, 1.49, 2.78, 4.25, 12.70, 2.23, 2.02, 6.09, 6.97, 0.15, 0.78, 4.03, 2.41, 6.75, 7.51, 1.93, 0.10, 5.99, 6.33, 9.06, 2.76, 0.98, 2.36, 0.15, 1.97, 0.07};
    public static final double[] REL_H_DEUTSCH = {6.51, 1.89, 3.06, 5.08, 17.40, 1.66, 3.01, 4.76, 7.55, 0.27, 1.21, 3.44, 2.53, 9.78, 2.51, 0.79, 0.02, 7.00, 7.27, 6.15, 4.35, 0.67, 1.89, 0.03, 0.04, 1.13};
    public static final double[] REL_H_FRANZOESISCH = {7.63, 0.90, 3.26, 3.66, 14.72, 1.07, 0.87, 0.74, 7.53, 0.55, 0.05, 5.45, 2.97, 7.09, 5.38, 3.02, 1.36, 6.55, 7.95, 7.23, 6.31, 1.63, 0.11, 0.39, 0.31, 0.14};

    private static final String GEHEIMTEXT_1 = "PWTMYTBADKDGPWPFYWFGUESOTLUPNVYWAPKCSOOJWWASTLSUZUSJMJBBRSTIMGPYSXOJWWASMMZQLCHJQWGYDHKOJWWASTMFPADWIPVKLHONZWPDPWRAAGQPRKNJCNPKGPJJLTHYOWOHPGYJWCUEKUZLGAOWKHOGPESMZMRWPBKVFVZTQNLAGSFSMVWTDPWRAAGQPRKNJCNPTGTKEOMSGVLYVCHKBVKLOFOBLGNCIVXWPLYBZAAEOOWKEWEODZKZOGPWGOMSWMPWTIFFLCTUTYGUOSLZSILYOHEWEODSRVVYHSFAVVHHWGIPTGHYHCWJVLERGJWKPDHGJWTUTQNBXGZEUKTWIAZPPMOGPWGJQWGYDHKNJCNPSOVWTZPFOMNQUQFGOWPYTQNBAIVOSXNSNZNVHMSPAHCXBWVDTFJRWFLASXAGPHYHCWJVLEOANWKUPTXIYGUFFSQLLHZRKZFGPYTXIYGUOWKVAEOEAOBBCVOSXVWKUMSGVLYVCHKBOGYOSTSGGUYSTAAPKYWIPLBBRSRIKULYJUVWKUPFHMDKLMWMMFRLCGUVKQSWAGVVWYNVLZSILYROMKKJSBAZSWMOWKHMILSCKZAIRPWZHMGPYSXLWTNCIVXWPIPNOMZGUSSXIMUIPYUUEGUKICMDEOPFMZMRWPGOMYGOZSXBOKLGWKTWHYLUKVEWZDAGVEKUOSYBWPZDHKTDGUFBJEWNJSSLZSILYYUMFPAPAGVKVLWZKV";
    private static final String GEHEIMTEXT_2 = "KQOWEFVJPUJUUNUKGLMEKJINMWUXFQMKJBGWRLFNFGHUDWUUMBSVLPSNCMUEKQCTESWREEKOYSSIWCTUAXYOTAPXPLWPNTCGOJBGFQHTDWXIZAYGFFNSXCSEYNCTSSPNTUJNYTGGWZGRWUUNEJUUQEAPYMEKQHUIDUXFPGUYTSMTFFSHNUOCZGMRUWEYTRGKMEEDCTVRECFBDJQCUSWVBPNLGOYLSKMTEFVJJTWWMFMWPNMEMTMHRSPXFSSKFFSTNUOCZGMDOEOYEEKCPJRGPMURSKHFRSEIUEVGOYCWXIZAYGOSAANYDOEOYJLWUNHAMEBFELXYVLWNOJNSIOFRWUCCESWKVIDGMUCGOCRUWGNMAAFFVNSIUDEKQHCEUCPFCMPVSUDGAVEMNYMAMVLFMAOYFNTQCUAFVFJNXKLNEIWCWODCCULWRIFTWGMUSWOVMATNYBUHTCOCWFYTNMGYTQMKBBNLGFBTWOJFTWGNTEJKNEEDCLDHWTVBUVGFBIJGYYIDGMVRDGMPLSWGJLAGOEEKJOFEKNYNOLRIVRWVUHEIWUURWGMUTJCDBNKGMBIDGMEEYGUOTDGGQEUJYOTVGGBRUJYS";
    private static final String GEHEIMTEXT_3 = "LIZTQYAFLWVQCEFLQCRKRQOOAUWXVNRPNZXHVQYZPLVBSZAWARAVTVDOQLGPDSDPYEGUDCWRAPUCMJHHVSJLSEEMTKYEUWLZERACMPLWGKRLNEIDEILFBKGAXVFKANHQMLTMEEXSETGIXHFSGZRVRKUXSFMCGIZSGPNPBRVUYEVMHZRANRVLVMCKVFNLHCTYTKNLPKQMYTZTGJQDAMFNRUMPBPVQYZPHEASRUEUKJWSILTRUDPKOCHCEGYETEAGCUBVWGTCAALTOXWJHHMQTDNJKNDTXUETRUEOPOQHVDHHJQLUAXGUYLFKZEVZMVAIGLMEGXRUZVQIJIRIQIDJLIEAUONAMDPYIH";
    private static final String GEHEIMTEXT_4 = "AZBBDPHMAKDDNOXGPQFGWNXMRWGQKAMNYSLOWHBDNMGDNABDDBWQAQLBDQYEADHQWVDDNTBDCMGDNOXGPHNLAZLSAVNMZNKZCBXHJMGLWBKNOMGMWOXMKALDSWAHJOXGPLBDNMBRAEBQXZBMCMGCQMGFAUBSPMEMWKALKATLXQDTJLDNIUXMIQMDEVXQHIWTJODZBNXDVCKTAKDFQBZDJWLRAEXHPMKLWKADJJXHIHPDEBXMOKAHBNWHAOEDEKADBZTFAVTFAVHROMPNDQGFAPMCEMKDEAXVEZAZXMGEWPKQWMWDNOXKWLXMZQXVEZSTCMGNOAXEELXKYILSNWUQEVZDJHNQQMVJGWFLAVPHNUBSAQGDNTTCQVZAWVTMAVZTPOXMKALDSMBSAZFZYPXMHMMYPMGCHQVGXMBLZZBSPMGRYPBEBVTFAVHROMPNDQGFAPMCEMKDEAXVEZUQEVZDJSTEBMXTJLUZJIGDJVTBDTXMEVZQWLNMZEHLEBDNIUMHDZSTNCXBGVTVEMBLIMKFIQMCAZXHOMGAWPG";
    private static final String GEHEIMTEXT_5 = "CWAQKIGIQQMIAIIIBFSEAOLTZLOEQIIJSPIMFIQDTSRSCHZICWAQKIGIQQMIAIIIXLRMARIVVVFSRWZWDSEZVMSPJUGXHRUOSJPBGKUEAUOXWEYVFYAZTILXZBKIEECWTPKZWXUJPMXHRRYISKOONSQRZDKVFRRGIOEUVMHWZZYXNVSAVCDMNMJIIMXIISEIJYEUYIUMXPZFRELJUCAOLJXIMHCIVNRLSPNIULUSHHAKRLVRVXDWJXGMKTUQNXZWDSEIMJJEWMTDHIIJVPLTWRGSMBQEZIIISDTUSPVQDBQVLTKSMZGQWMQOJVZEXXJGITELWVDYNLKQQMGPPXABAWFLZVJMRRJXBFSCFHZMYUKXRWZGIYAKZWHMIMXLRMIEUXIBEEUMZDGVNYJWDSLQWWVPDKNHRQJGICEQTIQYILJIEOICQEOTGKLIZZBIEJRWTEEUWLUEGAHYRGYISOIMTINEIVZIFXVRTTNLLVDMXBKHRGFQFEEAMRGXMIOGGIUIDSINXVHWWIYMRVVRELUNVIQMYMKRQIJFFYELAOWMIMXQBIEGIPSRGLDRIMYXEMKLFXICKFHWXPXMRFVVVYTMJEQHZZKQQMVRBNHQZQEIIITRGIMMHPNMJIYIMAILYYVWTPLCFKGMZAKKNPKPBYGMRILXVTYYAOEEDVBIJYQHZZYXHQWETEJIZVHRVKNZVKVRFCESGRQXZKNEEPVWCLBJSKHZDOKRRVVGITFNJMHVPVMIAWPWUPMILMVGCMTXMMWJFCNAULOMZAYPVGYZFCOMXJHROTOGUXVJSTELJMFLRQRLRPDOBDIACMHMIVGGUMYQCPNIFRWINDKVSEYVFYFCWVGMZJKWGMDQVYGLWVVGCTAIFWVPXZRBDRJIPVJIAXQMGQEZMRJHZAGPTSIMUSMCKAHRDOKVOIBEOYTQKXGMZIAXBOVCWTGMFIUIQMXWPLCYFDSMDYQKYQKMZKVKFYSILDCYMDOKRRVVFNHQXJUMZZARTHVYUWIKZWFLRQKVVKVVAFEVLDLJAMXRVWK";
    private static final String GEHEIMTEXT_6 = "MTCPLPLGCBRMPLKPECYXTVHYTYHQLLTAEOXCLKWEZUCANYLMYRABQNKLNOPMGQGYNYLBDTYHKNCLPTLGLZDLBEMVLXCINZLPSTLMLMTMNPZFLGSMTGHRDQUGPDGYLYIEOWPUFPXDMTZMLZDDNCLGCBRMPLKPNWLGQHGOGSCPKXCBPLNYCPKOTMTGBRDQUXTVGTZPZKJAEJGHNQBTHZENWLKKEGPCLPTLGLKJYHXHWNXSMPBFOWTAWTXNVFLBKZVSMCBYRIDLGKCGYYFMNSXYLQYMVIOLKPZUAFLTUTBESTFIEWNVZTMKUDZVVHDENWLYKMJUAFVFLKEAKLUKQIZVSQGKXCIWZWPUFPIWWOHMTAEOXYLKLGDBCBLFVFDBOUGAXDQEOGLKJZXTVGYAPQTHMXQVTTCQGCTCMCBLDKJSBPAUSBNPFLFDKJYXTJGUNYLFLKVZAWMZTQNBP";
    private static final String GEHEIMTEXT_7 = "VCAAIDRBQFXVUBUVQDHZJBPBHKVAHIHURAWTKBRRJVXSEJEJVSERVUHPNHQSOOGGARORSYYJVARRVSHFTGECVHRVRJDBQYMTKHFPLRWHRAXRJBNPLKWFNHQQHWGEELPYYNRXIOEOIYHFMFIVOSTRMJWYENJKPIGYMVESUBJWQIATJIHWURMKVHVYPVESJRKLQUERMJHKRTDZHZNAJRQURAHVIFNTIRQHJBVKVDVRPKDBMYMVGKBEXXHRNAOVEZVPOCDQURXIDBRSVVXBQSIZQRFGEUWRBEJWHBFGIIWIEFXIDGFRFIXQXRKRUHRAFCXARTVRVVVZQVOPYNYDRFTRRRESAQQZWHNTQZWHRERRFVGFSDPSEUIIEGGJMEWSESVLKZVAKXRZQFMCESEXYGISERMJQSORPJWIEZFCLHMQSEQSESYENSNFGYHFNHGYZSYYIZQGRYYWHFUBVZCCAGYELJREWLPGGRVEHBFGELEOORRKHIREKVKSVZRZVGPUPLVGRYXFUGPUPFVGFCMVJSYCJRGGPUVZWHNHKVQPYVGB";
    private static final String GEHEIMTEXT_8 = "WUBEFIQLZURMVOFEHMYMWTIXCGTMPIFKRZUPMVOIRQMMWOZMPULMBNYVQQQMVMVJLEYMHFEFNZPSDLPPSDLPEVQMWCXYMDAVQEEFIQCAYTQOWCXYMWMSEMEFCFWYEYQETRLIQYCGMTWCWFBSMYFPLRXTQYEEXMRULUKSGWFPTLRQAERLUVPMVYQYCXTWFQLMTELSFJPQEHMOZCIWCIWFPZSLMAEZIQVLQMZVPPXAWCSMZMORVGVVQSZETRLQZPBJAZVQIYXEWWOICCGDWHQMMVOWSGNTJPFPPAYBIYBJUTWRLQKLKLLLMDPYVACDCFQNZPIFPPKSDVPTIDGXMQQVEBMQALKEZMGCVKUZKIZBZLIUAMMVZ";


    public static void main(String[] args) {
//
//        RSA alice = new RSA();
//        System.out.println(alice);
//
//        RSA bob = new RSA();
//        System.out.println(bob);
//
//        // Alice verschlüsselt die Nachricht 123456 für Bob
//        BigInteger cypher = alice.encrypt(new BigInteger("123456"), bob.getE(), bob.getN());
//        System.out.println("cypher = " + cypher);
//        BigInteger message = bob.decrypt(cypher);
//        System.out.println("message = " + message);

        RSA bene = new RSA();

        Scanner scanner = new Scanner(System.in);

        System.out.println("Welcome to the RSA Public Key Generator");
        System.out.println("E: " + bene.getE());
        System.out.println("N: " + bene.getN());


        System.out.println(bene.toString());




        System.out.println("Cypher: ");
        BigInteger cypher = new BigInteger(ModMult.stringToBigInt(scanner.nextLine()).toByteArray());

        BigInteger message = bene.decrypt(cypher);


        System.out.print("E: ");
        BigInteger E = new BigInteger(scanner.nextLine());

        System.out.print("N: ");
        BigInteger N = new BigInteger(scanner.nextLine());

        System.out.println("E: " + E);
        System.out.println("N: " + N);



    }




}